services:
  customer-service:
    build:
      context: ./customer-service/.
      target: production
    environment:
      - NODE_ENV=production
    command: npm run dev
    depends_on:

  book-service:
    build:
      context: ./book-service/.
      target: production
    environment:
      - NODE_ENV=production
    command: npm run dev

  order-service:
    build:
      context: ./order-service/.
      target: production
    environment:
      - NODE_ENV=production
    command: npm run dev