services:
  customer-service:
    container_name: customer-container
    ports:
      - "3001:3001"
    env_file:
      - ./services/customer-service/.env

  book-service:
    container_name: book-container
    ports:
      - "3003:3003"
    env_file:
      - ./services/book-service/.env

  order-service:
    container_name: order-container
    ports:
      - "3002:3002"
    env_file:
      - ./services/order-service/.env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data:
